### ISSUE TITLE
txtclasses_rsicd data 

### ISSUE THREAD

**Issue by rongtongxueya** [alinlab/s-clip#1]
hello,Thank you for sharing such great code. But I have a question, what file is txtclasses_rsicd in your code? I tried to reproduce your code but could not find this file, this file has been confused for several days, could you give me some advice?
class RSICD_CLS(RSICD):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.load_class_info(os.path.join(self.root, "txtclasses_rsicd"))  -------this i dont understand

    def load_class_info(self, class_dir):
        classes = []
        path2class = {}
        for idx, fn in enumerate(sorted(os.listdir(class_dir))):
            classes.append(fn.split(".txt")[0])
            with open(os.path.join(class_dir, fn)) as f:
                for line in f.readlines():
                    path2class[line.strip()] = idx

        self.classes = classes
        self.path2class = path2class

**Comment by jts250** [comment]
https://github.com/201528014227051/RSICD_optimal
Recently I also encounter this, and I think you can find it here.

**Comment by sangwoomo** [comment]
Hi @rongtongxueya, I'm so sorry that I missed this issue! I think you can get the file from the link above. Thank you so much @jts250!
