### ISSUE TITLE
The method for generating keywords

### ISSUE THREAD

**Issue by chirmy** [alinlab/s-clip#3]
Hello:
Thank you for sharing such great code. But I have a question, I noticed in your paper the method for generating keywords: keywords can be obtained from class names or extracted by using algorithms like YAKE applied to captions. 
Could you please send me your program for generating keywords ?
Thanks.

**Comment by sangwoomo** [comment]
Hi, the code is very simple; just concatenate the texts and follow the instruction:
https://github.com/LIAAD/yake?tab=readme-ov-file#usage-python

**Comment by chirmy** [comment]
Thank you !
