### ISSUE TITLE
About train_info.json for Polyvore

### ISSUE THREAD

**Issue by Gank0078** [alinlab/s-clip#4]
Thank you for your amazing work! I want to run the code for fashion datasets, but I cannot find train_info.json for Polyvore. Could you tell me where to get this file? I downloaded the dataset from https://github.com/mvasil/fashion-compatibility, and is there something wrong? Looking forward to your reply!

**Comment by Gank0078** [comment]
The loading place is at https://github.com/alinlab/s-clip/blob/master/custom/data.py#L148

**Comment by sangwoomo** [comment]
Hi @Gank0078,

Several datasets have been generated by crawling images from the Polyvore site. We followed the FashionViL method (see [FashionViL paper](https://arxiv.org/abs/2207.08150)) to download the Polyvore dataset. This dataset was originally proposed in [this paper](https://arxiv.org/abs/1803.09196), and you can download it from the following links: [GitHub](https://github.com/mvasil/fashion-compatibility) or [Google Drive](https://drive.google.com/file/d/13-J4fAPZahauaGycw3j_YvbAHO7tOTW5/view).

Additionally, metadata can be found on the [FashionViL GitHub page](https://github.com/BrandonHanx/mmf).

Please note that the dataset instructions may have been updated and might not be compatible with the current version.

cc: @kimmk135

**Comment by Gank0078** [comment]
Thank you for your reply! I think it is very helpful to address my issue.
